pages_adminPages:
    resource: "@PagesBundle/Resources/config/routing/pages.yml"
    prefix:   /admin/pages

pages:
    pattern:  /page/{locale}/{slug}
    defaults: { _controller: PagesBundle:Pages:page }

contact:
    pattern:  /contact/{locale}
    defaults: { _controller: PagesBundle:Pages:contact }
home:
    pattern:  /page/{locale}/
    defaults: { _controller: PagesBundle:Pages:home }
